{"hierarchy":{"paths":[["doc:\/\/SwiftCU\/documentation\/SwiftCU","doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["Linux"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cudaErrorLaunchFailure","kind":"identifier"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/swiftcu\/cudaerror\/cudaerrorlaunchfailure"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError\/cudaErrorLaunchFailure"},"metadata":{"title":"cudaError.cudaErrorLaunchFailure","role":"symbol","externalID":"s:7SwiftCU9cudaErrorO0cD13LaunchFailureyA2CmF","roleHeading":"Case","modules":[{"name":"SwiftCU"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cudaErrorLaunchFailure"}],"symbolKind":"case"},"kind":"symbol","abstract":[{"text":"An exception occurred on the device while executing a kernel. Common","type":"text"},{"text":" ","type":"text"},{"text":"causes include dereferencing an invalid device pointer and accessing","type":"text"},{"text":" ","type":"text"},{"text":"out of bounds shared memory. Less common cases can be system specific - more","type":"text"},{"type":"text","text":" "},{"type":"text","text":"information about these cases can be found in the system specific user guide."},{"type":"text","text":" "},{"type":"text","text":"This leaves the process in an inconsistent state and any further CUDA work"},{"type":"text","text":" "},{"type":"text","text":"will return the same error. To continue using CUDA, the process must be terminated"},{"type":"text","text":" "},{"type":"text","text":"and relaunched."}],"references":{"doc://SwiftCU/documentation/SwiftCU/cudaError/cudaErrorLaunchFailure":{"kind":"symbol","identifier":"doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError\/cudaErrorLaunchFailure","title":"cudaError.cudaErrorLaunchFailure","role":"symbol","abstract":[{"type":"text","text":"An exception occurred on the device while executing a kernel. Common"},{"type":"text","text":" "},{"type":"text","text":"causes include dereferencing an invalid device pointer and accessing"},{"type":"text","text":" "},{"type":"text","text":"out of bounds shared memory. Less common cases can be system specific - more"},{"type":"text","text":" "},{"type":"text","text":"information about these cases can be found in the system specific user guide."},{"type":"text","text":" "},{"type":"text","text":"This leaves the process in an inconsistent state and any further CUDA work"},{"type":"text","text":" "},{"type":"text","text":"will return the same error. To continue using CUDA, the process must be terminated"},{"type":"text","text":" "},{"type":"text","text":"and relaunched."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cudaErrorLaunchFailure","kind":"identifier"}],"url":"\/documentation\/swiftcu\/cudaerror\/cudaerrorlaunchfailure","type":"topic"},"doc://SwiftCU/documentation/SwiftCU/cudaError":{"kind":"symbol","type":"topic","identifier":"doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"cudaError"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"cudaError"}],"title":"cudaError","url":"\/documentation\/swiftcu\/cudaerror","role":"symbol"},"doc://SwiftCU/documentation/SwiftCU":{"role":"collection","identifier":"doc:\/\/SwiftCU\/documentation\/SwiftCU","kind":"symbol","title":"SwiftCU","url":"\/documentation\/swiftcu","abstract":[],"type":"topic"}}}