{"variants":[{"paths":["\/documentation\/swiftcu\/cudaerror\/cudaerrorassert"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"An assert triggered in device code during kernel execution. The device"},{"type":"text","text":" "},{"type":"text","text":"cannot be used again. All existing allocations are invalid. To continue"},{"type":"text","text":" "},{"type":"text","text":"using CUDA, the process must be terminated and relaunched."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cudaErrorAssert"}],"platforms":["Linux"]}]}],"hierarchy":{"paths":[["doc:\/\/SwiftCU\/documentation\/SwiftCU","doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError"]]},"identifier":{"url":"doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError\/cudaErrorAssert","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","role":"symbol","externalID":"s:7SwiftCU9cudaErrorO0cD6AssertyA2CmF","modules":[{"name":"SwiftCU"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cudaErrorAssert"}],"roleHeading":"Case","title":"cudaError.cudaErrorAssert"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://SwiftCU/documentation/SwiftCU":{"identifier":"doc:\/\/SwiftCU\/documentation\/SwiftCU","title":"SwiftCU","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/swiftcu","kind":"symbol"},"doc://SwiftCU/documentation/SwiftCU/cudaError":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cudaError","kind":"identifier"}],"url":"\/documentation\/swiftcu\/cudaerror","kind":"symbol","navigatorTitle":[{"text":"cudaError","kind":"identifier"}],"identifier":"doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError","title":"cudaError","abstract":[],"type":"topic"},"doc://SwiftCU/documentation/SwiftCU/cudaError/cudaErrorAssert":{"url":"\/documentation\/swiftcu\/cudaerror\/cudaerrorassert","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cudaErrorAssert","kind":"identifier"}],"identifier":"doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError\/cudaErrorAssert","abstract":[{"text":"An assert triggered in device code during kernel execution. The device","type":"text"},{"text":" ","type":"text"},{"text":"cannot be used again. All existing allocations are invalid. To continue","type":"text"},{"text":" ","type":"text"},{"text":"using CUDA, the process must be terminated and relaunched.","type":"text"}],"title":"cudaError.cudaErrorAssert","type":"topic","kind":"symbol"}}}