{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError\/cudaErrorSynchronizationError"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/SwiftCU\/documentation\/SwiftCU","doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Linux"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cudaErrorSynchronizationError"}],"languages":["swift"]}]}],"sections":[],"metadata":{"title":"cudaError.cudaErrorSynchronizationError","symbolKind":"case","externalID":"s:7SwiftCU9cudaErrorO0cd15SynchronizationD0yA2CmF","role":"symbol","modules":[{"name":"SwiftCU"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cudaErrorSynchronizationError","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftcu\/cudaerror\/cudaerrorsynchronizationerror"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"This indicated that a synchronization operation had failed.","type":"text"},{"text":" ","type":"text"},{"text":"This was previously used for some device emulation functions.","type":"text"},{"text":" ","type":"text"},{"text":"\\deprecated","type":"text"},{"text":" ","type":"text"},{"text":"This error return is deprecated as of CUDA 3.1. Device emulation mode was","type":"text"},{"text":" ","type":"text"},{"text":"removed with the CUDA 3.1 release.","type":"text"}],"references":{"doc://SwiftCU/documentation/SwiftCU/cudaError":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cudaError","kind":"identifier"}],"url":"\/documentation\/swiftcu\/cudaerror","kind":"symbol","navigatorTitle":[{"text":"cudaError","kind":"identifier"}],"identifier":"doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError","title":"cudaError","abstract":[],"type":"topic"},"doc://SwiftCU/documentation/SwiftCU/cudaError/cudaErrorSynchronizationError":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cudaErrorSynchronizationError"}],"url":"\/documentation\/swiftcu\/cudaerror\/cudaerrorsynchronizationerror","abstract":[{"type":"text","text":"This indicated that a synchronization operation had failed."},{"type":"text","text":" "},{"type":"text","text":"This was previously used for some device emulation functions."},{"type":"text","text":" "},{"type":"text","text":"\\deprecated"},{"type":"text","text":" "},{"type":"text","text":"This error return is deprecated as of CUDA 3.1. Device emulation mode was"},{"type":"text","text":" "},{"type":"text","text":"removed with the CUDA 3.1 release."}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/SwiftCU\/documentation\/SwiftCU\/cudaError\/cudaErrorSynchronizationError","title":"cudaError.cudaErrorSynchronizationError"},"doc://SwiftCU/documentation/SwiftCU":{"identifier":"doc:\/\/SwiftCU\/documentation\/SwiftCU","title":"SwiftCU","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/swiftcu","kind":"symbol"}}}